import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/main.module.css";
import Navigation from "@/component/navigation";
import Footer from "@/component/footer";
import Game from "@/component/game";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>

        <title>Countrydle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Africa_from_low_orbiting_satellite_Suomi_NPP.jpg/1024px-Africa_from_low_orbiting_satellite_Suomi_NPP.jpg" />

      </Head>
       
      <main className={styles.background}>  
      <Navigation />
      <div className={styles.center}>
        <Game />
        <Footer />
      </div>
      </main>
    </>
  )
}